# 100 numpy exercises

This is a collection of exercises that have been collected in the numpy mailing list, on stack overflow
and in the numpy documentation. The goal of this collection is to offer a quick reference for both old
and new users but also to provide a set of exercises for those who teach.

#### 1. Import the numpy package under the name `np` (★☆☆)

In [2]:
import numpy as np

#### 2. Print the numpy version and the configuration (★☆☆)

In [2]:
import numpy as np

print(np.__version__)
np.show_config()

2.0.0
{
  "Compilers": {
    "c": {
      "name": "msvc",
      "linker": "link",
      "version": "19.29.30154",
      "commands": "cl"
    },
    "cython": {
      "name": "cython",
      "linker": "cython",
      "version": "3.0.10",
      "commands": "cython"
    },
    "c++": {
      "name": "msvc",
      "linker": "link",
      "version": "19.29.30154",
      "commands": "cl"
    }
  },
  "Machine Information": {
    "host": {
      "cpu": "x86_64",
      "family": "x86_64",
      "endian": "little",
      "system": "windows"
    },
    "build": {
      "cpu": "x86_64",
      "family": "x86_64",
      "endian": "little",
      "system": "windows"
    }
  },
  "Build Dependencies": {
    "blas": {
      "name": "scipy-openblas",
      "found": true,
      "version": "0.3.27",
      "detection method": "pkgconfig",
      "include directory": "C:/Users/runneradmin/AppData/Local/Temp/cibw-run-chs4gd90/cp310-win_amd64/build/venv/Lib/site-packages/scipy_openblas64/include",
      "lib 

c:\Python\lib\site-packages\numpy\__config__.py:155: UserWarning: Install `pyyaml` for better output
  warnings.warn("Install `pyyaml` for better output", stacklevel=1)


#### 3. Create a null vector of size 10 (★☆☆)

In [11]:
vec = np.zeros(10)
print(vec)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


#### 4. How to find the memory size of any array (★☆☆)

In [12]:
size = vec.nbytes
print(size)

80


#### 5. How to get the documentation of the numpy add function from the command line? (★☆☆)

In [13]:
help(np.add)

Help on ufunc:

add = <ufunc 'add'>
    add(x1, x2, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature])
    
    Add arguments element-wise.
    
    Parameters
    ----------
    x1, x2 : array_like
        The arrays to be added.
        If ``x1.shape != x2.shape``, they must be broadcastable to a common
        shape (which becomes the shape of the output).
    out : ndarray, None, or tuple of ndarray and None, optional
        A location into which the result is stored. If provided, it must have
        a shape that the inputs broadcast to. If not provided or None,
        a freshly-allocated array is returned. A tuple (possible only as a
        keyword argument) must have length equal to the number of outputs.
    where : array_like, optional
        This condition is broadcast over the input. At locations where the
        condition is True, the `out` array will be set to the ufunc result.
        Elsewhere, the `out` array will retai

#### 6. Create a null vector of size 10 but the fifth value which is 1 (★☆☆)

In [14]:
vec_2 = np.zeros(10)
vec_2[4] = 1 
print(vec_2)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


#### 7. Create a vector with values ranging from 10 to 49 (★☆☆)

In [16]:
vec_3 = np.arange(10, 50)

print(vec_3)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


#### 8. Reverse a vector (first element becomes last) (★☆☆)

In [18]:
vec_4 = np.array([1, 2, 3, 4, 5])
reversed_vector = vec_4[::-1]
print(reversed_vector)

[5 4 3 2 1]


#### 9. Create a 3x3 matrix with values ranging from 0 to 8 (★☆☆)

In [19]:
matrix = np.arange(9).reshape(3, 3)
print(matrix)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


#### 10. Find indices of non-zero elements from [1,2,0,0,4,0] (★☆☆)

In [20]:
arr = [1, 2, 0, 0, 4, 0]
indices = []

for i in range(len(arr)):
    if arr[i] != 0:
        indices.append(i)

print(indices)

[0, 1, 4]


#### 11. Create a 3x3 identity matrix (★☆☆)

In [21]:
i_matrix = np.array([[1, 0, 0], [0, 1, 0], [0, 0, 1]])
print(i_matrix)

[[1 0 0]
 [0 1 0]
 [0 0 1]]


#### 12. Create a 3x3x3 array with random values (★☆☆)

In [22]:
array_3d = np.random.random((3, 3, 3))
print(array_3d)

[[[0.09023998 0.93978061 0.27946888]
  [0.13189799 0.12213188 0.8671695 ]
  [0.10470904 0.25208961 0.21755716]]

 [[0.35673035 0.02347568 0.71056034]
  [0.56911221 0.41898958 0.64214523]
  [0.24733259 0.92895479 0.85405454]]

 [[0.80423048 0.01230914 0.91292349]
  [0.27006052 0.21267689 0.43344226]
  [0.42155756 0.8300662  0.46136036]]]


#### 13. Create a 10x10 array with random values and find the minimum and maximum values (★☆☆)

In [24]:
array_2d = np.random.random((10, 10))
print("Array: ",array_2d)
min_value = np.min(array_2d)
max_value = np.max(array_2d)
print(min_value)
print(max_value)

Array:  [[0.03860041 0.69583382 0.24000585 0.76332891 0.58308933 0.67487521
  0.60723432 0.25275317 0.22376451 0.87885143]
 [0.15364071 0.56897995 0.90695073 0.90343965 0.27660707 0.65290373
  0.67408556 0.36841111 0.38399221 0.8126824 ]
 [0.0821548  0.67659873 0.82442638 0.49309141 0.2842433  0.39680949
  0.67309968 0.30719666 0.80551264 0.4233143 ]
 [0.18957288 0.41080197 0.63761907 0.76201284 0.45082927 0.38764228
  0.81864058 0.57162402 0.13434624 0.18820807]
 [0.15005105 0.08755898 0.17794543 0.3920874  0.19796603 0.43249328
  0.76970572 0.0335947  0.98320398 0.16692455]
 [0.18180597 0.32116342 0.58812884 0.69264805 0.77843233 0.26974294
  0.81092853 0.13642027 0.20408032 0.3184631 ]
 [0.55274526 0.66148896 0.57399952 0.15072558 0.97611701 0.17729234
  0.40478831 0.71893342 0.73112545 0.27647712]
 [0.31793032 0.89538379 0.52282644 0.91282395 0.78349819 0.54421221
  0.65980646 0.11101462 0.01190331 0.49826423]
 [0.71293069 0.25015603 0.15111973 0.78099045 0.90441166 0.53192414
  0.

#### 14. Create a random vector of size 30 and find the mean value (★☆☆)

In [26]:
vec_5 = np.random.random(30)
print(vec_5)
mean = np.mean(vec_5)
print("Mean = ", mean)

[1.83274350e-01 1.06216358e-01 1.40180921e-01 9.70231696e-01
 1.19627934e-01 2.48175964e-01 8.18431600e-02 7.10345626e-01
 4.87526623e-02 3.54623986e-01 4.79091890e-01 4.76212676e-01
 1.76394865e-01 5.57278915e-01 6.00354290e-02 5.07057263e-02
 5.43942198e-01 9.92080655e-01 4.87560645e-01 3.09825018e-01
 6.22519907e-01 6.28908791e-02 8.01656430e-01 4.32856893e-01
 9.49894337e-01 2.71894546e-04 8.78553122e-01 9.04868803e-01
 3.52975935e-01 7.58251175e-01]
Mean =  0.428704668226701


#### 15. Create a 2d array with 1 on the border and 0 inside (★☆☆)

In [27]:
array_2d = np.zeros((5, 5))

array_2d[0, :] = 1
array_2d[-1, :] = 1
array_2d[:, 0] = 1
array_2d[:, -1] = 1

print(array_2d)

[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


#### 16. How to add a border (filled with 0's) around an existing array? (★☆☆)

In [30]:
og_array = np.ones((3, 3))
rows, cols = og_array.shape
new_array = np.zeros((rows + 2, cols + 2))
new_array[1:-1, 1:-1] = og_array
print(new_array)


[[0. 0. 0. 0. 0.]
 [0. 1. 1. 1. 0.]
 [0. 1. 1. 1. 0.]
 [0. 1. 1. 1. 0.]
 [0. 0. 0. 0. 0.]]


#### 17. What is the result of the following expression? (★☆☆)
```python
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
np.nan in set([np.nan])
0.3 == 3 * 0.1
```

In [35]:
print(0 * np.nan)
print(np.nan == np.nan)
print(np.inf > np.nan)
print(np.nan - np.nan)
print(np.nan in set([np.nan]))
print(0.3 == 3 * 0.1)


nan
False
False
nan
True
False


#### 18. Create a 5x5 matrix with values 1,2,3,4 just below the diagonal (★☆☆)

In [38]:
mat = np.zeros((5, 5))
np.fill_diagonal(mat[0:], [1, 2, 3, 4,5])

print(mat)

[[1. 0. 0. 0. 0.]
 [0. 2. 0. 0. 0.]
 [0. 0. 3. 0. 0.]
 [0. 0. 0. 4. 0.]
 [0. 0. 0. 0. 5.]]


#### 19. Create a 8x8 matrix and fill it with a checkerboard pattern (★☆☆)

In [44]:
matrix = np.zeros((8, 8), dtype=int)

matrix[::2, ::2] = 1  
matrix[1::2, 1::2] = 1  

print(matrix)

[[1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]]


#### 20. Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element? (★☆☆)

In [4]:
shape = (6, 7, 8)

big_array = np.random.random(shape)

index = 99

indices = np.unravel_index(index, shape)

value = big_array[indices]

print(f"Indices (x, y, z) of the 100th element: {indices}")
print(f"Value of the 100th element: {value}")


Indices (x, y, z) of the 100th element: (np.int64(1), np.int64(5), np.int64(3))
Value of the 100th element: 0.2197660725779237


#### 21. Create a checkerboard 8x8 matrix using the tile function (★☆☆)

In [5]:

unit = np.array([[1, 0],
                [0, 1]])
board = np.tile(unit, (4, 4))

print(board)


[[1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]]


#### 22. Normalize a 5x5 random matrix (★☆☆)

In [6]:
rand_matrix = np.random.randint(1, 11, size=(5, 5))
min_val = np.min(rand_matrix)
max_val = np.max(rand_matrix)

normalized_matrix = (rand_matrix - min_val) / (max_val - min_val)

print("Original Random Matrix:")
print(rand_matrix)
print("\nNormalized Matrix:")
print(normalized_matrix)

Original Random Matrix:
[[ 5  8  2  7  1]
 [ 2  4  8  3  2]
 [ 2  3  7 10  8]
 [ 4  2  2  5  6]
 [ 6  5  9  9  1]]

Normalized Matrix:
[[0.44444444 0.77777778 0.11111111 0.66666667 0.        ]
 [0.11111111 0.33333333 0.77777778 0.22222222 0.11111111]
 [0.11111111 0.22222222 0.66666667 1.         0.77777778]
 [0.33333333 0.11111111 0.11111111 0.44444444 0.55555556]
 [0.55555556 0.44444444 0.88888889 0.88888889 0.        ]]


#### 23. Create a custom dtype that describes a color as four unsigned bytes (RGBA) (★☆☆)

#### 24. Multiply a 5x3 matrix by a 3x2 matrix (real matrix product) (★☆☆)

In [2]:
import numpy as np
matrix1 = np.random.random((5, 3))
matrix2 = np.random.random((3, 2))
result = np.dot(matrix1, matrix2)


print("5x3 Matrix:")
print(matrix1)
print("\n3x2 Matrix:")
print(matrix2)
print("\nResult of 5x3 * 3x2:")
print(result)


5x3 Matrix:
[[0.11410117 0.8546486  0.06981991]
 [0.40674341 0.91828675 0.16776374]
 [0.3621762  0.30090702 0.71282627]
 [0.62735918 0.27655142 0.4406595 ]
 [0.22308941 0.12154837 0.12083321]]

3x2 Matrix:
[[0.785474   0.86813346]
 [0.22390757 0.05818478]
 [0.71451526 0.02956827]]

Result of 5x3 * 3x2:
[[0.33087318 0.15084704]
 [0.64496748 0.41149837]
 [0.8611806  0.35300253]
 [0.86955422 0.57375212]
 [0.2887837  0.20431648]]


#### 25. Given a 1D array, negate all elements which are between 3 and 8, in place. (★☆☆)

In [3]:
array4 = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])

for i in range(len(array4)):
    if 3 <= array4[i] <= 8:
        array4[i] *= -1

print(array4)

[ 1  2 -3 -4 -5 -6 -7 -8  9 10]


#### 26. What is the output of the following script? (★☆☆)
```python
# Author: Jake VanderPlas

print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))
```

In [4]:
print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))

9
10


#### 27. Consider an integer vector Z, which of these expressions are legal? (★☆☆)
```python
Z**Z
2 << Z >> 2
Z <- Z
1j*Z
Z/1/1
Z<Z>Z
```

In [6]:
Z = np.array([1, 2, 3, 4, 5])

print("Z**Z:", Z ** Z)
print("2 << Z >> 2:", 2 << Z >> 2)
print("Z < -Z:", Z < -Z)
print("1j * Z:", 1j * Z)
print("Z / 1 / 1:", Z / 1 / 1)

print("Z < Z > Z:", Z < Z > Z)



Z**Z: [   1    4   27  256 3125]
2 << Z >> 2: [ 1  2  4  8 16]
Z < -Z: [False False False False False]
1j * Z: [0.+1.j 0.+2.j 0.+3.j 0.+4.j 0.+5.j]
Z / 1 / 1: [1. 2. 3. 4. 5.]


ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()

#### 28. What are the result of the following expressions? (★☆☆)
```python
np.array(0) / np.array(0)
np.array(0) // np.array(0)
np.array([np.nan]).astype(int).astype(float)
```

In [8]:
result1 = np.array(0) / np.array(0)
print(result1)

result2 = np.array(0) // np.array(0)
print(result2)

result3 = np.array([np.nan]).astype(int).astype(float)
print(result3)


nan
0
[-9.22337204e+18]


C:\Users\agrim\AppData\Local\Temp\ipykernel_8932\3510652603.py:1: RuntimeWarning: invalid value encountered in divide
  result1 = np.array(0) / np.array(0)
C:\Users\agrim\AppData\Local\Temp\ipykernel_8932\3510652603.py:4: RuntimeWarning: divide by zero encountered in floor_divide
  result2 = np.array(0) // np.array(0)
C:\Users\agrim\AppData\Local\Temp\ipykernel_8932\3510652603.py:7: RuntimeWarning: invalid value encountered in cast
  result3 = np.array([np.nan]).astype(int).astype(float)


#### 29. How to round away from zero a float array ? (★☆☆)

In [9]:
array5 = np.array([-1.7, -0.2, 0.2, 1.7])
rounded_array = np.where(array5 > 0, np.ceil(array5), np.floor(array5))

print(rounded_array)

[-2. -1.  1.  2.]


#### 30. How to find common values between two arrays? (★☆☆)

In [11]:
array1 = np.array([1, 2, 3, 4, 5])
array2 = np.array([4, 5, 6, 7, 8])

common_values = np.intersect1d(array1, array2)

print(common_values)

[4 5]


#### 31. How to ignore all numpy warnings (not recommended)? (★☆☆)

In [12]:
import warnings
warnings.filterwarnings('ignore')

result1 = np.array(0) / np.array(0)
result2 = np.array(0) // np.array(0)
result3 = np.array([np.nan]).astype(int).astype(float)

print(result1, result2, result3)

warnings.filterwarnings('default')


nan 0 [-9.22337204e+18]


#### 32. Is the following expressions true? (★☆☆)
```python
np.sqrt(-1) == np.emath.sqrt(-1)
```

In [18]:

bool = np.sqrt(-1) == np.emath.sqrt(-1)
print(bool)


False


C:\Users\agrim\AppData\Local\Temp\ipykernel_8932\147444540.py:1: RuntimeWarning: invalid value encountered in sqrt
  bool = np.sqrt(-1) == np.emath.sqrt(-1)


#### 33. How to get the dates of yesterday, today and tomorrow? (★☆☆)

In [19]:
from datetime import datetime, timedelta

today = datetime.now().date()
yesterday = today - timedelta(days=1)
tomorrow = today + timedelta(days=1)

print("Yesterday:", yesterday)
print("Today:", today)
print("Tomorrow:", tomorrow)


Yesterday: 2024-07-12
Today: 2024-07-13
Tomorrow: 2024-07-14


#### 34. How to get all the dates corresponding to the month of July 2016? (★★☆)

In [20]:
start_date = datetime(2016, 7, 1)
days = 31  
JulyDates = []

for day in range(days):
    date = start_date + timedelta(days=day)
    JulyDates.append(date.date())  

print(JulyDates)


[datetime.date(2016, 7, 1), datetime.date(2016, 7, 2), datetime.date(2016, 7, 3), datetime.date(2016, 7, 4), datetime.date(2016, 7, 5), datetime.date(2016, 7, 6), datetime.date(2016, 7, 7), datetime.date(2016, 7, 8), datetime.date(2016, 7, 9), datetime.date(2016, 7, 10), datetime.date(2016, 7, 11), datetime.date(2016, 7, 12), datetime.date(2016, 7, 13), datetime.date(2016, 7, 14), datetime.date(2016, 7, 15), datetime.date(2016, 7, 16), datetime.date(2016, 7, 17), datetime.date(2016, 7, 18), datetime.date(2016, 7, 19), datetime.date(2016, 7, 20), datetime.date(2016, 7, 21), datetime.date(2016, 7, 22), datetime.date(2016, 7, 23), datetime.date(2016, 7, 24), datetime.date(2016, 7, 25), datetime.date(2016, 7, 26), datetime.date(2016, 7, 27), datetime.date(2016, 7, 28), datetime.date(2016, 7, 29), datetime.date(2016, 7, 30), datetime.date(2016, 7, 31)]


#### 35. How to compute ((A+B)*(-A/2)) in place (without copy)? (★★☆)

In [22]:
A = np.array([1, 2, 3])
B = np.array([4, 5, 6])

result = ((A + B) * (-A / 2))

print(result)

[ -2.5  -7.  -13.5]


#### 36. Extract the integer part of a random array of positive numbers using 4 different methods (★★☆)

In [23]:

random_array = np.random.rand(5) * 10  

int_part1 = np.floor(random_array)

int_part2 = np.trunc(random_array)

int_part3 = random_array.astype(int)

int_part4 = np.int_(random_array)

print("Original array:", random_array)
print("Method 1 (np.floor):", int_part1)
print("Method 2 (np.trunc):", int_part2)
print("Method 3 (astype(int)):", int_part3)
print("Method 4 (np.int_):", int_part4)


Original array: [5.86750412 5.48285399 1.79233733 4.62482167 2.82204117]
Method 1 (np.floor): [5. 5. 1. 4. 2.]
Method 2 (np.trunc): [5. 5. 1. 4. 2.]
Method 3 (astype(int)): [5 5 1 4 2]
Method 4 (np.int_): [5 5 1 4 2]


#### 37. Create a 5x5 matrix with row values ranging from 0 to 4 (★★☆)

In [24]:
matrix_6 = np.zeros((5, 5)) + np.arange(5)

print(matrix_6)

[[0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]]


#### 38. Consider a generator function that generates 10 integers and use it to build an array (★☆☆)

In [27]:
def generate_integers():
    integers = []
    for i in range(10):
        integers.append(i)
    return integers

new_integers = generate_integers()

array = np.array(new_integers)

print(array)

[0 1 2 3 4 5 6 7 8 9]


#### 39. Create a vector of size 10 with values ranging from 0 to 1, both excluded (★★☆)

In [2]:
import numpy as np
vector = np.linspace(0, 1, 12)[1:-1]

print(vector)

[0.09090909 0.18181818 0.27272727 0.36363636 0.45454545 0.54545455
 0.63636364 0.72727273 0.81818182 0.90909091]


#### 40. Create a random vector of size 10 and sort it (★★☆)

In [6]:
vector = np.random.randint(low=0, high=11, size=10)

print("Original vector:", vector)
sort = np.sort(vector)

print("Sorted vector:", sort)

Original vector: [ 4  2  4  7 10  0  8  1  8  1]
Sorted vector: [ 0  1  1  2  4  4  7  8  8 10]


#### 41. How to sum a small array faster than np.sum? (★★☆)

In [10]:
array_10 = np.array([1, 2, 3, 4, 5])
sum_result = sum(array_10)
print("Sum :", sum_result)

Sum : 15


#### 42. Consider two random array A and B, check if they are equal (★★☆)

#### 43. Make an array immutable (read-only) (★★☆)

#### 44. Consider a random 10x2 matrix representing cartesian coordinates, convert them to polar coordinates (★★☆)

#### 45. Create random vector of size 10 and replace the maximum value by 0 (★★☆)

#### 46. Create a structured array with `x` and `y` coordinates covering the [0,1]x[0,1] area (★★☆)

#### 47. Given two arrays, X and Y, construct the Cauchy matrix C (Cij =1/(xi - yj)) (★★☆)

#### 48. Print the minimum and maximum representable value for each numpy scalar type (★★☆)

#### 49. How to print all the values of an array? (★★☆)

#### 50. How to find the closest value (to a given scalar) in a vector? (★★☆)

#### 51. Create a structured array representing a position (x,y) and a color (r,g,b) (★★☆)

#### 52. Consider a random vector with shape (100,2) representing coordinates, find point by point distances (★★☆)

#### 53. How to convert a float (32 bits) array into an integer (32 bits) in place?

#### 54. How to read the following file? (★★☆)
```
1, 2, 3, 4, 5
6,  ,  , 7, 8
 ,  , 9,10,11
```

#### 55. What is the equivalent of enumerate for numpy arrays? (★★☆)

#### 56. Generate a generic 2D Gaussian-like array (★★☆)

#### 57. How to randomly place p elements in a 2D array? (★★☆)

#### 58. Subtract the mean of each row of a matrix (★★☆)

#### 59. How to sort an array by the nth column? (★★☆)

#### 60. How to tell if a given 2D array has null columns? (★★☆)

#### 61. Find the nearest value from a given value in an array (★★☆)

#### 62. Considering two arrays with shape (1,3) and (3,1), how to compute their sum using an iterator? (★★☆)

#### 63. Create an array class that has a name attribute (★★☆)

#### 64. Consider a given vector, how to add 1 to each element indexed by a second vector (be careful with repeated indices)? (★★★)

#### 65. How to accumulate elements of a vector (X) to an array (F) based on an index list (I)? (★★★)

#### 66. Considering a (w,h,3) image of (dtype=ubyte), compute the number of unique colors (★★☆)

#### 67. Considering a four dimensions array, how to get sum over the last two axis at once? (★★★)

#### 68. Considering a one-dimensional vector D, how to compute means of subsets of D using a vector S of same size describing subset  indices? (★★★)

#### 69. How to get the diagonal of a dot product? (★★★)

#### 70. Consider the vector [1, 2, 3, 4, 5], how to build a new vector with 3 consecutive zeros interleaved between each value? (★★★)

#### 71. Consider an array of dimension (5,5,3), how to mulitply it by an array with dimensions (5,5)? (★★★)

#### 72. How to swap two rows of an array? (★★★)

#### 73. Consider a set of 10 triplets describing 10 triangles (with shared vertices), find the set of unique line segments composing all the  triangles (★★★)

#### 74. Given a sorted array C that corresponds to a bincount, how to produce an array A such that np.bincount(A) == C? (★★★)

#### 75. How to compute averages using a sliding window over an array? (★★★)

#### 76. Consider a one-dimensional array Z, build a two-dimensional array whose first row is (Z[0],Z[1],Z[2]) and each subsequent row is  shifted by 1 (last row should be (Z[-3],Z[-2],Z[-1]) (★★★)

#### 77. How to negate a boolean, or to change the sign of a float inplace? (★★★)

#### 78. Consider 2 sets of points P0,P1 describing lines (2d) and a point p, how to compute distance from p to each line i (P0[i],P1[i])? (★★★)

#### 79. Consider 2 sets of points P0,P1 describing lines (2d) and a set of points P, how to compute distance from each point j (P[j]) to each line i (P0[i],P1[i])? (★★★)

#### 80. Consider an arbitrary array, write a function that extract a subpart with a fixed shape and centered on a given element (pad with a `fill` value when necessary) (★★★)

#### 81. Consider an array Z = [1,2,3,4,5,6,7,8,9,10,11,12,13,14], how to generate an array R = [[1,2,3,4], [2,3,4,5], [3,4,5,6], ..., [11,12,13,14]]? (★★★)

#### 82. Compute a matrix rank (★★★)

#### 83. How to find the most frequent value in an array?

#### 84. Extract all the contiguous 3x3 blocks from a random 10x10 matrix (★★★)

#### 85. Create a 2D array subclass such that Z[i,j] == Z[j,i] (★★★)

#### 86. Consider a set of p matrices with shape (n,n) and a set of p vectors with shape (n,1). How to compute the sum of of the p matrix products at once? (result has shape (n,1)) (★★★)

#### 87. Consider a 16x16 array, how to get the block-sum (block size is 4x4)? (★★★)

#### 88. How to implement the Game of Life using numpy arrays? (★★★)

#### 89. How to get the n largest values of an array (★★★)

#### 90. Given an arbitrary number of vectors, build the cartesian product (every combinations of every item) (★★★)

#### 91. How to create a record array from a regular array? (★★★)

#### 92. Consider a large vector Z, compute Z to the power of 3 using 3 different methods (★★★)

#### 93. Consider two arrays A and B of shape (8,3) and (2,2). How to find rows of A that contain elements of each row of B regardless of the order of the elements in B? (★★★)

#### 94. Considering a 10x3 matrix, extract rows with unequal values (e.g. [2,2,3]) (★★★)

#### 95. Convert a vector of ints into a matrix binary representation (★★★)

#### 96. Given a two dimensional array, how to extract unique rows? (★★★)

#### 97. Considering 2 vectors A & B, write the einsum equivalent of inner, outer, sum, and mul function (★★★)

#### 98. Considering a path described by two vectors (X,Y), how to sample it using equidistant samples (★★★)?

#### 99. Given an integer n and a 2D array X, select from X the rows which can be interpreted as draws from a multinomial distribution with n degrees, i.e., the rows which only contain integers and which sum to n. (★★★)

#### 100. Compute bootstrapped 95% confidence intervals for the mean of a 1D array X (i.e., resample the elements of an array with replacement N times, compute the mean of each sample, and then compute percentiles over the means). (★★★)